name: Sample Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      environment: "dev"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Script
      run: echo "Performing $environment task at $(date)."

